### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mxdyzmx** [YangguangZhou/Luogu-User-Card#3]
ID:575480
https://api.jerryz.com.cn/practice?id=575480&dark_mode=true&disable_cache=true
https://api.jerryz.com.cn/shield?id=575480
这两个网址在获取时会报500

**Comment by Dark-Monarch-Samurai** [comment]
有时基本信息卡死，加载不出来，只有个图片png格式的样子

**Comment by YangguangZhou** [comment]
现在似乎正常了
